#!/bin/sh

SERVICE_NAME="container-monitor"

remove() {
    printf "\033[32m Post Remove of a normal remove\033[0m\n"

    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper mask "${SERVICE_NAME}.service" >/dev/null
    elif [ -x systemd ]; then
        systemctl stop "${SERVICE_NAME}.service"
        systemctl disable "${SERVICE_NAME}.service"
    elif [ -x "/etc/init.d/${SERVICE_NAME}" ]; then
        "/etc/init.d/${SERVICE_NAME}" stop
        rm -f "/etc/init.d/${SERVICE_NAME}"
    fi
}

purge() {
    printf "\033[32m Post Remove purge, deb only\033[0m\n"
    rm -rf "/etc/${SERVICE_NAME:?}"
}

upgrade() {
    printf "\033[32m Post Remove of an upgrade\033[0m\n"
}

echo "$@"

action="$1"

case "$action" in
  "0" | "remove")
    remove
    ;;
  "1" | "upgrade")
    upgrade
    ;;
  "purge")
    purge
    ;;
  *)
    printf "\033[32m Alpine\033[0m"
    remove
    ;;
esac
