#!/bin/sh

SERVICE_NAME="tedge-container-monitor"
CONFIGURATION_DIR="/etc/${SERVICE_NAME:?}"

remove() {
    printf "\033[32m Post Remove of a normal remove\033[0m\n"

    # Remove conf dir if empty (as rpm/apk do not have purge mechanism like debian)
    if [ -d "$CONFIGURATION_DIR" ]
    then
      if [ -z "$(ls -A "$CONFIGURATION_DIR")" ]; then
        rm -rf "$CONFIGURATION_DIR"
      fi
    fi
}

purge() {
    printf "\033[32m Post Remove purge, deb only\033[0m\n"
    rm -rf "$CONFIGURATION_DIR"
}

upgrade() {
    printf "\033[32m Post Remove of an upgrade\033[0m\n"
}

echo "$@"

action="$1"

case "$action" in
  "0" | "remove")
    remove
    ;;
  "1" | "upgrade")
    upgrade
    ;;
  "purge")
    purge
    ;;
  *)
    printf "\033[32m Alpine\033[0m"
    remove
    ;;
esac
