#!/bin/sh
set -e

SERVICE_NAME="tedge-container-monitor"

stop_services() {
    if [ -d /run/systemd/system ] && command -V deb-systemd-invoke >/dev/null 2>&1; then
        deb-systemd-invoke stop "${SERVICE_NAME}.service" >/dev/null ||:
    elif [ -d /run/systemd/system ] && command -V deb-systemd-invoke >/dev/null 2>&1; then
        systemctl stop "${SERVICE_NAME}.service" >/dev/null ||:
    fi

    if [ -x "/etc/init.d/${SERVICE_NAME}" ] || [ -e "/etc/init/${SERVICE_NAME}.conf" ]; then
        "/etc/init.d/${SERVICE_NAME}" stop || :
    fi
}

remove() {
    printf "\033[32m Pre Remove of a normal remove\033[0m\n"
    stop_services
}

upgrade() {
    printf "\033[32m Pre Remove of an upgrade\033[0m\n"
    stop_services
}

echo "Running pre-remove: $*"

action="$1"

case "$action" in
    "0" | "remove")
        remove
        ;;
    "1" | "upgrade")
        upgrade
        ;;
    *)
        printf "\033[32m Alpine\033[0m"
        remove
        ;;
esac
