#!/bin/sh
set -e

SERVICE_NAME="tedge-container-plugin"

remove() {
    printf "\033[32m Post Remove of a normal remove\033[0m\n"

    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
    fi

    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper purge "${SERVICE_NAME}.service" >/dev/null
        deb-systemd-helper unmask "${SERVICE_NAME}.service" >/dev/null
    elif command -V systemctl >/dev/null 2>&1; then
        systemctl unmask "${SERVICE_NAME}.service" >/dev/null
    fi
}

purge() {
    printf "\033[32m Post Remove purge, deb only\033[0m\n"
}

upgrade() {
    printf "\033[32m Post Remove of an upgrade\033[0m\n"
}

action="$1"

case "$action" in
    "0" | "remove")
        remove
        ;;
    "1" | "upgrade")
        upgrade
        ;;
    "purge")
        purge
        ;;
    *)
        printf "\033[32m Alpine\033[0m"
        remove
        ;;
esac
