#!/command/with-contenv sh
if [ "${SERVICE_TEDGE_CONTAINER_PLUGIN:-1}" -eq 0 ]; then
    # Disable service and don't start again
    # https://github.com/just-containers/s6-overlay/issues/394
    s6-svc -O .
    exit 0
fi

exec 2>&1

SUDO=
if command -V sudo >/dev/null 2>&1; then
    SUDO="sudo"
fi

exec $SUDO /usr/bin/tedge-container run --config /etc/tedge-container-plugin/config.toml
