#!/bin/sh
set -e

ACTION="$1"
shift

get_credentials() {
    IMAGE="$1"
    # Write log messages to stderr
    echo "Retrieving private repository credentials for $IMAGE" >&2

    # Fetch some credentials from anywhere, e.g. api, local file storage, keychain etc.

    # Then return credentials
    cat <<EOT
{
    "username": "@@USERNAME@@",
    "password": "@@PASSWORD@@"
}
EOT
}

case "$ACTION" in
    get)
        get_credentials "$@"
        ;;
    *)
        echo "Unknown command" >&2
        exit 1
        ;;
esac

exit 0
