#!/bin/sh
set -e

ACTION="$1"
shift

get_credentials() {
    IMAGE="$1"
    USE_CACHE=1
    if [ "$2" = "--refresh" ]; then
        USE_CACHE=0
        echo "Refreshing credentials by deleting any stored cache" >&2
    fi

    if [ "$USE_CACHE" = 1 ]; then
        echo "Using cached private repository credentials for $IMAGE" >&2
        cat <<EOT
{
    "username": "invalid",
    "password": "invalid"
}
EOT
    else
        # Fetch some credentials from anywhere, e.g. api, local file storage, keychain etc.
        echo "Retrieving private repository credentials for $IMAGE" >&2
        cat <<EOT
{
    "username": "@@USERNAME@@",
    "password": "@@PASSWORD@@"
}
EOT
    fi
}

case "$ACTION" in
    get)
        get_credentials "$@"
        ;;
    *)
        echo "Unknown command" >&2
        exit 1
        ;;
esac

exit 0
