#!/bin/sh
set -e

CONTAINER_CLI=
CONTAINER_CLI_OPTIONS="docker podman nerdctl"
SETTINGS_FILE=/etc/tedge-container-plugin/env

# Only read the file if it has the correct permissions, to prevent people from editing it
# and side-loading functions
SETTINGS_FILE=/etc/tedge-container-plugin/env
FOUND_FILE=
if [ -f "$SETTINGS_FILE" ]; then
    FOUND_FILE=$(find "$SETTINGS_FILE" -perm 644 | head -1)
fi

if [ -n "$FOUND_FILE" ]; then
    echo "Loading setting file: $SETTINGS_FILE" >&2
    # Note: automatically export sourced variables to the environment
    # as cli commands need to react to variables such as: DOCKER_HOST
    set -a
    # shellcheck disable=SC1091,SC1090
    . "$SETTINGS_FILE"
    set +a
fi

# Detect which container cli is available
if [ -z "$CONTAINER_CLI" ]; then
    for cli in $CONTAINER_CLI_OPTIONS; do
        if command -v "$cli" >/dev/null 2>&1; then
            echo "Using $cli as the container cli" >&2
            CONTAINER_CLI="$cli"
            break
        fi
    done
fi

# script is being sourced
"$CONTAINER_CLI" "$@"
