#!/bin/sh
set -e

EXIT_OK=0
EXIT_USAGE=1
EXIT_FAILURE=2
# EXIT_RETRY=3

usage() {
    echo "
USAGE
    Docker plugin for thin-edge.io

    $0 <COMMAND> [MODULE_NAME] [--module-version [VERSION]] [--file [FILE]]

    $0 install <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 list
    $0 remove <MODULE_NAME> [--module-version [VERSION]]
    $0 prepare <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 finalize <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    $0 update-list <MODULE_NAME> [--module-version [VERSION]] [--file [FILE]]
    "
}

log() { echo "$@" >&2; }

if [ $# -lt 1 ]; then
    log "Invalid number of positional arguments."
    usage
    exit "$EXIT_USAGE"
fi

COMMAND="$1"
shift
MODULE_VERSION=latest
FILE=

# settings
VALIDATE_TAR_CONTENTS=0
CONTAINER_CLI=
CLI_OPTIONS="docker podman nerdctl"

# Detect which container cli is available
if [ -z "$CONTAINER_CLI" ]; then
    for cli in $CLI_OPTIONS; do
        if command -v "$cli" >/dev/null 2>&1; then
            log "Using $cli as the container cli"
            CONTAINER_CLI="$cli"
            break
        fi
    done
fi

# argument parsing
while [ $# -gt 0 ]; do
  case "$1" in
    --module-version)
        MODULE_VERSION="$2"
        shift
        ;;
    --file)
        FILE="$2"
        shift
        ;;
    -h|--help)
        usage
        exit "$EXIT_USAGE"
        ;;
    --*|-*)
        log "Unknown option $1"
        exit "$EXIT_USAGE"
        ;;
    *)
        MODULE_NAME="$1"

        if [ -z "$MODULE_NAME" ]; then
            log "Ignoring unknown positional argument: $1"
        fi
      ;;
  esac
  shift
done

if ! command -v "$CONTAINER_CLI" >/dev/null 2>&1; then
    log "$CONTAINER_CLI is not installed"
    exit "$EXIT_FAILURE"
fi

if ! "$CONTAINER_CLI" ps >/dev/null 2>&1; then
    log "$CONTAINER_CLI does not have permissions to run"
    exit "$EXIT_FAILURE"
fi

case "$COMMAND" in
    list)
        # Get all container and lookup the image id related to it
        # The version is a combination of the tag (human friendly) and the id (for uniqueness), e.g. Version="{Tag}@{Id}"
        "$CONTAINER_CLI" ps -a --format "{{.Names}}\t{{.Image}}" | while read -r line; do
            ITEM_NAME=$(echo "$line" | cut -f1)
            ITEM_IMAGE=$(echo "$line" | cut -f2 | sed 's/\(.*\)/\1/')
            ITEM_VERSION=$("$CONTAINER_CLI" image ls "$ITEM_IMAGE" --format "{{.Tag}}@{{.ID}}")

            printf '%s\t%s\n' "$ITEM_NAME" "$ITEM_VERSION"
        done
        ;;

    install)
        # Import container image
        if [ -z "$FILE" ]; then
            log "Pulling image: ${MODULE_VERSION}"
            "$CONTAINER_CLI" pull "${MODULE_VERSION}"
        elif [ -f "$FILE" ]; then
            log "Loading image from file: $FILE"
            CMD_OUTPUT=$("$CONTAINER_CLI" load --input "$FILE" 2>&1)
            log "$CONTAINER_CLI output: $CMD_OUTPUT"
            PARTS=$(echo "$CMD_OUTPUT" | tail -n 1 | sed 's/Loaded image: \+//g')
            TAR_IMAGE_NAME=$(echo "$PARTS" | cut -d':' -f1)
            TAR_IMAGE_TAG=$(echo "$PARTS" | cut -d':' -f2)

            # Validate the image/tag against expected fields
            if [ "$VALIDATE_TAR_CONTENTS" = 1 ]; then
                if [ "${TAR_IMAGE_NAME}:${TAR_IMAGE_TAG}" != "${MODULE_VERSION}" ]; then
                    log "Container image file does not match expected image/tag. got=${TAR_IMAGE_NAME}:${TAR_IMAGE_TAG}, wanted=${MODULE_NAME}:${MODULE_VERSION}"
                    exit "$EXIT_FAILURE"
                else
                    log "Container image matched expected image/tag"
                fi
            fi
        else
            log "Failed to load image. File does not exist: $FILE"
            exit "$EXIT_FAILURE"
        fi

        # Start container
        if "$CONTAINER_CLI" inspect "${MODULE_NAME}" >/dev/null 2>&1; then
            log "Stopping existing container before recreating"
            "$CONTAINER_CLI" stop "${MODULE_NAME}" || true
            "$CONTAINER_CLI" rm "${MODULE_NAME}" || true
        fi

        "$CONTAINER_CLI" run \
            -d \
            --publish-all \
            --name "${MODULE_NAME}" \
            "${MODULE_VERSION}"
        ;;

    remove)
        # don't fail if it does not exist
        log "Removing container: ${MODULE_NAME}:${MODULE_VERSION}"
        "$CONTAINER_CLI" stop "${MODULE_NAME}" || true
        "$CONTAINER_CLI" rm "${MODULE_NAME}" || true
        ;;

    prepare)
        ;;

    finalize)
        log "Removing unused images"
        "$CONTAINER_CLI" image prune --force
        ;;

    update-list)
        TAB=$(echo t | tr t \\t)
        while IFS="$TAB" read -r ACTION MODULE VERSION FILE
        do
            sh -c "$0 '$ACTION' '$MODULE' --module-version '$VERSION' --file '$FILE'"
        done
        ;;
esac

exit "$EXIT_OK"
