#!/bin/sh
####################################################################
# Monitor the container status and report it back to thin-edge.io
####################################################################
set -e

usage() {
    echo "
Monitor the container status and report it back to thin-edge.io.

When it is called without any arguments, then it will continously monitor the status periodically. It will
only exist when it receives a kill signal (e.g. ctrl-c etc.).

When a container name is passed as a positional argument, then it will only get the status of the container
and then exit (this is called ONE-SHOT mode).

OVERVIEW

    +------------+     +------------+     +------------+     +------------+
    ! containers ! <-> !  monitor   ! <-> !   broker   ! <-> !   tedge    !
    +------------+     +------------+     +------------+     +------------+
                                                +
                                                +    +------------+
                                                +--> !   cloud    !
                                                     +------------+

USAGE
    $0 [container_name] [--interval <seconds>] [--container-cli <docker|podman|nerdctl>] [--telemetry|--no-telemetry]

POSITIONAL ARGS
    container_name      Name of the container to check in one-shot mode.

FLAGS
    --container-cli <path>         Container cli, e.g. docker, podman, nerdctl. If left blank that it will be automatically detected
    --log-level <string>           Log level. error, warn, info, debug, none. 'info' will be used if an invalid value is given
    --telemetry/--no-telemetry     Publish telemetry data about the containers (e.g. cpu, memory, network io)
    --meta/--no-meta               Publish meta information about the conatiners (e.g. id, image name, ports etc.)
    --interval <seconds>           Interval in seconds which the container status will be reported. This is the minimum interval between checks
                                   (not including the time it takes to read the status)

EXAMPLES
    $0
    Start the continous monitor. The status of all containers will be checked every <interval> seconds.

    $0 mycontainer-name
    Report the status of the 'mycontainer-name' container name (if it exists) once then exit
    "
}

# Log levels: 1=error, 2=warn, 3=info, 4=debug, >=5 none
LOG_LEVEL=${LOG_LEVEL:-3}
LOG_TIMESTAMPS=${LOG_TIMESTAMPS:-1}

timestamp() {
    [ "$LOG_TIMESTAMPS" = "1" ] && date +"%Y-%m-%dT%H:%M:%S%z " || echo ""
}

# logging
log() { level="$1"; shift; echo "$(timestamp)[pid=$$] $level $*" >&2; }
debug() { if [ -n "$LOG_LEVEL" ] && [ "$LOG_LEVEL" -ge 4 ]; then log "DEBUG" "$@" >&2; fi }
info() { if [ -n "$LOG_LEVEL" ] && [ "$LOG_LEVEL" -ge 3 ]; then log "INFO" "$@" >&2; fi }
warn() { if [ -n "$LOG_LEVEL" ] && [ "$LOG_LEVEL" -ge 2 ]; then log "WARN" "$@" >&2; fi }
error() { if [ -n "$LOG_LEVEL" ] && [ "$LOG_LEVEL" -ge 1 ]; then log "ERROR" "$@" >&2; fi }

convert_loglevel() {
    level=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    case "$level" in
        4|debug|trace) echo 4;;
        3|info|information) echo 3;;
        2|warn|warning) echo 2;;
        1|error) echo 1;;
        0|none) echo 0;;
        *)
            echo "WARN Invalid log level ('$1'). Using 'info' level instead" >&2
            echo 3;;
    esac
}

get_loglevel_name() {
    level=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    case "$level" in
        4|debug|trace) echo debug;;
        3|info|information) echo info;;
        2|warn|warning) echo warn;;
        1|error) echo error;;
        0|none) echo none;;
        *)
            echo "WARN Invalid log level. Using 'warn' level instead" >&2
            echo warn;;
    esac
}

on_reload() {
    info "Received SIGHUP signal"
    load_settings || :
}

load_settings() {
    # Don't allow this to be configured, as the user could change the setting in the
    # file being sourced
    SETTINGS_FILE=/etc/tedge-container-plugin/env

    # Only read the file if it has the correct permissions, to prevent people from editing it
    # and side-loading functions
    FOUND_FILE=$(find "$SETTINGS_FILE" -perm 644 | head -1)

    if [ -n "$FOUND_FILE" ]; then
        debug "Reloading setting file: $SETTINGS_FILE"
        # shellcheck disable=SC1091,SC1090
        . "$SETTINGS_FILE"

        # Convert log level before using any of the log helpers!
        LOG_LEVEL=$(convert_loglevel "$LOG_LEVEL")
        info "Current log level: $(get_loglevel_name "$LOG_LEVEL") ($LOG_LEVEL)"
        info "Current interval: ${INTERVAL} (seconds)"
    else
        if [ -f "$SETTINGS_FILE" ]; then
            warn "Settings file has insecure permissions. It will be ignored. Please change the permissions to using 'chmod 644 \"$SETTINGS_FILE\""
        else
            warn "Skipping settings file as it does not exist. file=$SETTINGS_FILE"
        fi
    fi

    info "Successfully loaded settings"
}

load_settings

#
# Defaults
#
CONTAINER_CLI_OPTIONS="${CONTAINER_CLI_OPTIONS:-docker podman nerdctl}"
CONTAINER_CLI=${CONTAINER_CLI:-}
COMPOSE_CLI=${COMPOSE_CLI:-}
MONITOR_COMPOSE_PROJECTS=${MONITOR_COMPOSE_PROJECTS:-1}

INTERVAL=${INTERVAL:-60}
TELEMETRY=${TELEMETRY:-1}
META_INFO=${META_INFO:-1}

# Only used if tedge cli is not installed
MQTT_HOST=${MQTT_HOST:-127.0.0.1}
MQTT_PORT=${MQTT_PORT:-1883}

# Internals
SERVICE_NAME="tedge-container-monitor"
SERVICE_TYPE="${SERVICE_TYPE:-container}"
GROUP_SERVICE_TYPE="${GROUP_SERVICE_TYPE:-"container-group"}"
SUB_PID=
TAB=$(printf '\t')

#
# Argument parsing
#
POSITIONAL=
while [ $# -gt 0 ]; do
    case "$1" in
        --help|-h)
            usage
            exit 0
            ;;

        --interval)
            INTERVAL="$2"
            shift
            ;;

        --container-cli)
            CONTAINER_CLI="$2"
            shift
            ;;

        --log-level)
            LOG_LEVEL="$2"
            shift
            ;;

        --telemetry)
            TELEMETRY=1
            ;;
        --no-telemetry)
            TELEMETRY=0
            ;;

        --meta)
            META_INFO=1
            ;;
        --no-meta)
            META_INFO=0
            ;;

        *)
            if [ -n "$POSITIONAL" ]; then
                POSITIONAL="$POSITIONAL $1"
            else
                POSITIONAL="$1"
            fi
            ;;
    esac
    shift
done

# shellcheck disable=SC2086
set -- $POSITIONAL

# topic config
TOPIC_ROOT=$(tedge config get mqtt.topic_root || echo 'te')
TOPIC_ID=$(tedge config get mqtt.device_topic_id || echo 'device/main//')

TOPIC_PREFIX="$TOPIC_ROOT/device/main"
case "$TOPIC_ID" in
    */*//)
        parent="$(echo "$TOPIC_ID" | sed 's/\/*$//')"
        TOPIC_PREFIX="$TOPIC_ROOT/$parent"
        ;;
esac

register_service() {
    name="$1"
    type="$2"
    message=$(printf '{"@type":"service","name":"%s","type":"%s"}' "$name" "$type")
    publish_retain "$TOPIC_PREFIX/service/$name" "$message" ||:
}

publish_health() {
    SERVICE_NAME="$1"
    MESSAGE="$2"
    publish_retain "$TOPIC_PREFIX/service/$SERVICE_NAME/status/health" "$MESSAGE" ||:
}

# -------------------
# Helpers
# -------------------
command_exists() { command -v "$1" >/dev/null 2>&1; }

is_positive_int() {
    if [ -z "$1" ]; then
        return 1
    fi
    case "$1" in
        ''|*[!0-9]*) return 1 ;;
        *) return 0 ;;
    esac
}

is_running() {
  # shellcheck disable=SC2009
  # Use ps/grep fallback as busybox does not support the "ps -p" option
  ps | grep "^[[:blank:]]*$1" >/dev/null 2>&1
}

#
# Auto-set values (if not already set)
#

LOG_LEVEL=$(convert_loglevel "$LOG_LEVEL")

if command_exists tedge; then
    if [ -z "$MQTT_HOST" ]; then
        MQTT_HOST=$(tedge config list | grep "^mqtt.bind_address=" | sed 's/^.*=//g')
    fi
    if [ -z "$MQTT_PORT" ]; then
        MQTT_PORT=$(tedge config list | grep "^mqtt.port=" | sed 's/^.*=//g')
    fi
fi

# Detect which container cli is available, choose the first one found
if [ -z "$CONTAINER_CLI" ]; then
    for cli in $CONTAINER_CLI_OPTIONS; do
        if command -v "$cli" >/dev/null 2>&1; then
            info "Using $cli as the container cli"
            CONTAINER_CLI="$cli"
            break
        fi
    done
fi

# Check if telemetry data is supported
if [ -n "$CONTAINER_CLI" ] && [ "$TELEMETRY" = "1" ]; then
    if ! "$CONTAINER_CLI" stats --all --no-stream --format "{{.ID}}\t{{.Name}}\t{{.CPUPerc}}\t{{.MemPerc}}\t{{.NetIO}}" > /dev/null 2>&1; then
        error "'$CONTAINER_CLI stats --all --no-stream' command failed. This is common if you are running it from inside a container. Disabling container stats collection"
        TELEMETRY=0
    fi
fi

if [ "$MONITOR_COMPOSE_PROJECTS" != "0" ]; then
    if [ -z "$COMPOSE_CLI" ]; then
        if docker compose >/dev/null 2>&1; then
            COMPOSE_CLI="docker compose"
        elif command -v "docker-compose" >/dev/null 2>&1; then
            COMPOSE_CLI="docker-compose"
        elif command -v "podman-compose" >/dev/null 2>&1; then
            COMPOSE_CLI="podman-compose"
        else
            warn "Could not find a docker compose compatible cli. Disabling compose project monitoring"
            MONITOR_COMPOSE_PROJECTS=0
        fi
    fi
fi

startup(){
    info "Registering signal handlers"
    # Clear any existing traps
    trap - INT QUIT ABRT TERM
    trap - HUP

    trap cleanup INT QUIT ABRT TERM
    trap on_reload HUP

    listen &
    SUB_PID=$!
    info "Started background health-check listener. pid=$SUB_PID"

    register_service "$SERVICE_NAME" "service"
    MESSAGE=$(printf '{"status":"up"}')
    publish_health "$SERVICE_NAME" "$MESSAGE"
}

listen() {
    if ! command_exists mosquitto_sub; then
        warn "'mosquitto_sub' is not installed. The tedge-container-monitor on-demand request listener requires 'mosquitto_sub' to be installed"
        return
    fi
    info "Subscribing to health-check messages"
    # Subscribe to the health-check topic, and just pass the topic to
    # this same script (to do a single on-demand health check for the given service)
    mosquitto_sub \
        --id "mosquitto_sub_${SERVICE_NAME}" \
        -h "$MQTT_HOST" \
        -p "$MQTT_PORT" \
        --will-topic "$TOPIC_PREFIX/service/${SERVICE_NAME}/status/health" \
        --will-payload "{\"status\":\"down\"}" \
        --will-retain \
        -t "$TOPIC_PREFIX/service/+/cmd/health/check" \
        -F '%t' | while read -r topic; do
            name=$(echo "$topic" | cut -d/ -f 5)
            info "Checking health of $name"
            check_health "$name" || :
        done
}

cleanup() {
    info "Shutting down"
    info "Clearing traps"

    trap - INT QUIT ABRT TERM
    trap - HUP

    if [ -n "$SUB_PID" ]; then
        info "Stopping background listener. pid=$SUB_PID"
        kill "$SUB_PID" >/dev/null 2>&1 || :
    fi
    # try sending a manual message (not relying on the last will and testament)
    publish_health "$SERVICE_NAME" '{"status":"down"}' || :

    info "Exiting"
    # Kill all child processes
    # https://spin.atomicobject.com/2017/08/24/start-stop-bash-background-process/
    kill 0 ||:
}

publish() {
    TOPIC="$1"
    MESSAGE="$2"

    debug "[$TOPIC] $MESSAGE"

    if command -v tedge >/dev/null 2>&1; then
        tedge mqtt pub "$TOPIC" "$MESSAGE" || error "Failed to publish message"
    elif command -v mosquitto_pub >/dev/null 2>&2; then
        mosquitto_pub -h "$MQTT_HOST" -p "$MQTT_PORT" -t "$TOPIC" -m "$MESSAGE" || error "Failed to publish message"
    else
        warn "Could not publish message. Reason: No mqtt client found"
    fi
}

publish_retain() {
    TOPIC="$1"
    MESSAGE="$2"

    debug "[$TOPIC] $MESSAGE"

    if command -v tedge >/dev/null 2>&1; then
        # We actuall want globbing here, as sometimes options are provided and sometimes not
        # shellcheck disable=SC2086
        tedge mqtt pub -r "$TOPIC" "$MESSAGE" || error "Failed to publish message"
    elif command -v mosquitto_pub >/dev/null 2>&2; then
        # We actuall want globbing here, as sometimes options are provided and sometimes not
        # shellcheck disable=SC2086
        mosquitto_pub -r -h "$MQTT_HOST" -p "$MQTT_PORT" -t "$TOPIC" -m "$MESSAGE" || error "Failed to publish message"
    else
        warn "Could not publish message. Reason: No mqtt client found"
    fi
}

check_health() {
    NAMES=""

    # optionally filter by specific name
    if [ $# -gt 0 ]; then
        NAMES="$1"
    fi

    "$CONTAINER_CLI" ps -a --format "{{.Names}}\t{{.State}}\t{{.Labels}}" --filter "name=$NAMES" | grep -v "com.docker.compose" | while IFS=$TAB read -r NAME STATE _OTHER; do
        # Normalize state, as podman returns a human friendly output, e.g. "Exited (0) 10 seconds ago"
        STATE=${STATE%% *}
        STATE=$(echo "$STATE" | tr '[:upper:]' '[:lower:]')
        debug "$CONTAINER_CLI ps -a: $STATE"
        case "$STATE" in
            running|up)
                STATUS="up"
                ;;
            *)
                STATUS="down"
                ;;
        esac
        register_service "$NAME" "$SERVICE_TYPE"
        MESSAGE=$(printf '{"status":"%s"}' "$STATUS")
        publish_health "$NAME" "$MESSAGE"
    done

    # Check docker compose projects
    if [ "$MONITOR_COMPOSE_PROJECTS" = 1 ]; then
        debug "Checking compose projects"
        # Filtering is not supported for these names!
        "$CONTAINER_CLI" ps --no-trunc --all --format "{{or .Labels \" \"}}\t{{or .State \" \"}}\t{{.Label \"com.docker.compose.project\" }}\t{{.Label \"com.docker.compose.service\" }}" | grep "com.docker.compose" | while IFS=$TAB read -r _LABELS STATE PROJECT_NAME PROJECT_SERVICE_NAME; do
            CLOUD_SERVICE_NAME="${PROJECT_NAME}@${PROJECT_SERVICE_NAME}"
            STATE=${STATE%% *}
            STATE=$(echo "$STATE" | tr '[:upper:]' '[:lower:]')
            info "State: service=$CLOUD_SERVICE_NAME, state=$STATE"
            case "$STATE" in
                running*|up*)
                    STATUS="up"
                    ;;
                create*)
                    STATUS="created"
                    ;;
                *)
                    STATUS="down"
                    ;;
            esac

            register_service "$CLOUD_SERVICE_NAME" "$GROUP_SERVICE_TYPE"
            MESSAGE=$(printf '{"status":"%s"}' "$STATUS")
            publish_health "$CLOUD_SERVICE_NAME" "$MESSAGE"
        done
    fi
}

check_container_info() {
    #
    # Collect container meta information and add it to the managed object
    #
    if [ "$META_INFO" = 1 ]; then

        NAMES=""
        # optionally filter by specific name
        if [ $# -gt 0 ]; then
            NAMES="$1"
        fi

        debug "Collecting container meta information"
        # Note: Use json template func in --format to allow docker to do the json escaping
        "$CONTAINER_CLI" ps --no-trunc --all --filter "name=$NAMES" --format "{{.ID}}\t{{or .Names \" \"}}\t{{or .Labels \" \"}}\t{{or .State \" \"}}\t{{or .Status \" \"}}\t{{.CreatedAt}}\t{{.Image}}\t{{or .Ports \" \"}}\t{{or .Networks \" \"}}\t{{or .RunningFor \" \"}}\t{{or .Size \" \"}}\t{{json (or .Command \" \")}}" | grep -v "com.docker.compose" | while IFS=$TAB read -r ID NAME _LABELS STATE STATUS CREATEDAT IMAGE PORTS NETWORKS RUNNINGFOR SIZE COMMAND; do
            if [ -n "${NAME%% }" ]; then
                message=$(printf '{"containerId":"%s","state":"%s","containerStatus":"%s","createdAt":"%s","image":"%s","ports":"%s","networks":"%s","runningFor":"%s","filesystem":"%s","command":%s}' "${ID%% }" "${STATE%% }" "${STATUS%% }" "${CREATEDAT%% }" "${IMAGE%% }" "${PORTS%% }" "${NETWORKS%% }" "${RUNNINGFOR%% }" "${SIZE%% }" "${COMMAND%% }")
                publish_retain "$TOPIC_PREFIX/service/$NAME/twin/container" "$message"
            fi
        done

        if [ "$MONITOR_COMPOSE_PROJECTS" = 1 ]; then
            debug "Collecting container-group meta information"
            # Note: Project filtering is not supported!
            # Note: Use json template func in --format to allow docker to do the json escaping
            # --filter "name=$NAMES"
            "$CONTAINER_CLI" ps --no-trunc --all --format "{{.ID}}\t{{or .Names \" \"}}\t{{or .Labels \" \"}}\t{{or .State \" \"}}\t{{or .Status \" \"}}\t{{.CreatedAt}}\t{{.Image}}\t{{or .Ports \" \"}}\t{{or .Networks \" \"}}\t{{or .RunningFor \" \"}}\t{{or .Size \" \"}}\t{{json (or .Command \" \")}}\t{{.Label \"com.docker.compose.project\" }}\t{{.Label \"com.docker.compose.service\" }}" | grep "com.docker.compose" | while IFS=$TAB read -r ID NAME _LABELS STATE STATUS CREATEDAT IMAGE PORTS NETWORKS RUNNINGFOR SIZE COMMAND PROJECT_NAME PROJECT_SERVICE_NAME; do
                CLOUD_SERVICE_NAME="${PROJECT_NAME}@${PROJECT_SERVICE_NAME}"
                if [ -n "${CLOUD_SERVICE_NAME%% }" ]; then
                    message=$(printf '{"containerId":"%s","containerName":"%s","state":"%s","containerStatus":"%s","createdAt":"%s","image":"%s","ports":"%s","networks":"%s","runningFor":"%s","filesystem":"%s","command":%s,"projectName":"%s","serviceName":"%s"}' "${ID%% }" "${NAME%% }" "${STATE%% }" "${STATUS%% }" "${CREATEDAT%% }" "${IMAGE%% }" "${PORTS%% }" "${NETWORKS%% }" "${RUNNINGFOR%% }" "${SIZE%% }" "${COMMAND%% }" "${PROJECT_NAME}" "${PROJECT_SERVICE_NAME}")
                    publish_retain "$TOPIC_PREFIX/service/$CLOUD_SERVICE_NAME/twin/container" "$message"
                fi
            done
        fi
    fi
}

check_telemetry() {
    #
    # Optional container statistics
    #
    # TODO: Exclude metrics for docker compose containers (as their names will not match the project name)
    # TODO: Support uptime of a container
    #   docker inspect -f '{{.State.StartedAt}}    {{.State.FinishedAt}}' mqtt-broker
    #   started_at=$(date --date "$(docker inspect -f '{{.State.StartedAt}}{{.State.FinishedAt}}' mqtt-broker)" +'%s')
    if [ "$TELEMETRY" = 1 ]; then

        debug "Collecting container stats"
        # Get list of containers which are not docker compose projects
        CONTAINERS=$("$CONTAINER_CLI" ps -a --format "{{or .Names \" \"}}\t{{.Labels}}" | grep -v "com.docker.compose" | cut -f1 | tr '\n' ' ')
        if [ -n "$CONTAINERS" ]; then
            # shellcheck disable=SC2046,SC2116
            "$CONTAINER_CLI" stats --all --no-stream --format "{{.Name}}\t{{.CPUPerc}}\t{{.MemPerc}}\t{{.NetIO}}" $(echo "$CONTAINERS") | while IFS=$TAB read -r NAME CPU_PERC MEM_PERC NET_IO; do
                NET_IO=$(echo "$NET_IO" | sed 's/[^0-9.].*//g')

                # Publish service metrics
                message=$(printf '{"container":{"cpu":%s,"memory":%s,"netio":%s}}' "${CPU_PERC%%%*}" "${MEM_PERC%%%*}" "${NET_IO}")
                publish "$TOPIC_PREFIX/service/$NAME/m/resource_usage" "$message"
            done
        else
            debug "No containers found, therefore no metrics to collect"
        fi

        debug "Collecting container-group stats"
        # Get list of containers which are docker compose projects
        CONTAINERS=$("$CONTAINER_CLI" ps --format "{{or .Names \" \"}}\t{{.Labels}}" | grep "com.docker.compose" | cut -f1 | tr '\n' ' ')

        if [ -n "$CONTAINERS" ]; then
            # shellcheck disable=SC2046,SC2116
            "$CONTAINER_CLI" stats --all --no-stream --format "{{.Name}}\t{{.CPUPerc}}\t{{.MemPerc}}\t{{.NetIO}}" $(echo "$CONTAINERS") | while IFS=$TAB read -r NAME CPU_PERC MEM_PERC NET_IO; do
                # lookup compose project and service name
                CLOUD_SERVICE_NAME=$("$CONTAINER_CLI" ps -a --format "{{.Label \"com.docker.compose.project\" }}@{{.Label \"com.docker.compose.service\" }}" --filter "name=$NAME")
                NET_IO=$(echo "$NET_IO" | sed 's/[^0-9.].*//g')

                # Publish service metrics
                message=$(printf '{"container":{"cpu":%s,"memory":%s,"netio":%s}}' "${CPU_PERC%%%*}" "${MEM_PERC%%%*}" "${NET_IO}")
                publish "$TOPIC_PREFIX/service/$CLOUD_SERVICE_NAME/m/resource_usage" "$message"
            done
        else
            debug "No container-groups found, therefore no metrics to collect"
        fi
    fi
}

wait_interval() {
    if ! is_positive_int "$INTERVAL"; then
        BAD_INTERVAL="$INTERVAL"
        INTERVAL=60
        warn "Invalid interval value '$BAD_INTERVAL'. Expected a positive integer representing seconds. Using default value '$INTERVAL'"
    fi
    debug "INTERVAL=$INTERVAL"
    if [ -n "$INTERVAL" ] && [ "$INTERVAL" -gt 0 ]; then
        # Sleep in the background so the traps can still be received
        sleep "$INTERVAL" &

        # Don't fail, as sleep could have been killed by another signal
        wait $! || :
    fi
}

main() {
    startup

    # Number of internvals to skip before potentially activating the telemetry metrics
    # as the services must register first, otherwise the measurements will cause a child
    # device to be registered instead of a service (child addition)
    skip_cycles=${SKIP_CYCLES:-5}
    while :; do

        # Check if background listener is still running
        if [ -n "$SUB_PID" ]; then
            if ! is_running "$SUB_PID"; then
                error "Background health-check listener is no longer running. Re-initializing"
                startup
            fi
        fi

        check_health

        if [ "$skip_cycles" -lt 1 ]; then
            check_telemetry
            check_container_info
        else
            skip_cycles=$((skip_cycles-1))
            debug "Skipping telemetry interval (remaining intervals=$skip_cycles)"
        fi
        wait_interval
    done
}

if ! command_exists "$CONTAINER_CLI"; then
    error "No container cli was detected. The following options were checked: '$CONTAINER_CLI_OPTIONS'"
    error "Exiting"
    exit 1
fi

# Single health check
if [ $# -gt 0 ] && [ "$1" != "*" ]; then
    NAME="${1#*/*/}"
    info "Checking health of $NAME"
    check_health "$NAME"

    if [ "$META_INFO" = 1 ]; then
        check_container_info "$NAME"
    fi

    if [ "$TELEMETRY" = 1 ]; then
        check_telemetry
    fi
    exit 0
fi

# Continuous health check
main
